projectName = "jco"
theme = "jco"
template = "jcore3"
localDomain = "jco.localhost"
domains = ["jco.localhost"]
remoteDomain = "new.jco.fi"
remoteHost = "jco@gb.bojaco.com"
remotePath = "files"
replace = ["//jco.gb.bojaco.com|//jco.localhost"]
branch = "gintonic"
pluginInstall = "composer"
dbPrefix = "zpp_"
