name: Deploy site

on:
  push:
    branch:
      - main

jobs:
  build:
    uses: jco-digital/deploy-wp-action/.github/workflows/build-project.yml@v3.0.1
    with:
      platform: ubuntu-latest
      fetch_submodules: true
      php_version: 8.2
      slack_channel: CU8LPT03W
    secrets: inherit
  deploy:
    needs: [build]
    uses: jco-digital/deploy-wp-action/.github/workflows/server-deploy.yml@v3.0.1
    with:
      platform: ubuntu-latest
      server_url: jco@gh.bojaco.com
      base_path: files
      paths: >-
        wp-content/themes/jco/:wp-content/themes/jco/,
        wp-content/plugins/:wp-content/plugins/,
        vendor/:vendor/
      slack_channel: CU8LPT03W
    secrets: inherit
