name: Deploy site

on:
  push:
    branch:
      - develop
      - main

jobs:
  build:
    uses: jco-digital/deploy-wp-action/.github/workflows/build-project.yml@v3.0.3
    with:
      php_version: 8.2
      slack_channel: CU8LPT03W
    secrets: inherit
  deploy-develop:
    needs: [build]
    if: github.ref == 'refs/heads/develop'
    uses: jco-digital/deploy-wp-action/.github/workflows/server-deploy.yml@v3.0.3
    with:
      server_url: jco@gb.bojaco.com
      base_path: files
      paths: >-
        wp-content/themes/jco/:wp-content/themes/jco/,
        wp-content/plugins/:wp-content/plugins/,
        vendor/:vendor/,
        wp-content/plugins/dynamic-archive/:wp-content/plugins/dynamic-archive/,
        wp-content/mu-plugins/module-loader.php:wp-content/mu-plugins/
      slack_channel: CU8LPT03W
    secrets: inherit
